name: build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml
